### PR TITLE
Pages

### PR DESCRIPTION
**Pull request by shreyasskdev**

### CODE REVIEW

**Comment by shreyasskdev** [comment]
feat: Cart comming soon page added

**Comment by shreyasskdev** [comment]
Any issues or changes.. Comment here

**Comment by shreyasskdev** [comment]
This branch has no conflicts with the base branch when rebasing

**Review by VAISHAKH-GK — COMMENTED** [review]
Change submit query button to search

**Comment by shreyasskdev** [comment]
Change submit query button to search

**Review by VAISHAKH-GK — APPROVED** [review]

**Pull request merged**
